name: ggrn
channels:
  - pytorch
  - nvidia
  - pyg
  - conda-forge
  - bioconda
  - defaults
  - lingfeiwang
dependencies:
  - python-duckdb
  - pytorch-lightning
  - scipy
  - pytorch   
  - pytorch-cuda=11.8
  - pyg
  - torchvision 
  - torchaudio 
  - numpy[version='<=1.23']
  - cython
  - scikit-learn
  - pyarrow
  - python=3.9
  - jupyterlab
  - jupyter
  - ipywidgets
  - yaml
  - wandb
  - selenium=3.141.0
  - altair
  - altair_saver
  - dcor
  - velocyto.py
  - scanpy
  - python-igraph
  - louvain
  - genomepy
  - gimmemotifs[version'<=0.17.1']
  - gseapy
  - goatools
  - python-annoy
  - pyreadr
  - regex
  - scikit-misc
  - dictys
  - tensorboard
