name: ggrn
channels:
  - pytorch
  - pyg
  - conda-forge
  - bioconda
  - defaults
  - lingfeiwang
dependencies:
  - pandas[version'>=2.0']
  - python-duckdb
  - pytorch-lightning
  - scipy
  - pytorch
  - torchtext
  - torchvision 
  - torchaudio 
  - numpy[version='<=1.23']
  - cython
  - scikit-learn
  - pyarrow
  - python=3.9
  - jupyterlab
  - jupyter
  - ipywidgets
  - yaml
  - wandb
  - selenium=3.141.0
  - altair
  - altair_saver
  - dcor
  - scanpy
  - python-igraph
  - louvain
  - genomepy
  - goatools
  - python-annoy
  - pyreadr
  - regex
  - scikit-misc
  - matplotlib[version'>=3.4,<3.5']
  - rpy2
  - anndata2ri
  - deprecated
  - datasets
  - gseapy
  - dictys
  - velocyto.py
  - pyg
  - tensorboard[version'>=2.4,<2.5']
  - gimmemotifs[version'==0.17.1']
  - transformers
  - accelerate
  - hyperopt
  - grpcio[version'<=1.49']
  - memray
