name: ggrn_minimal
channels:
  - pytorch
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.9
  - pandas[version'>=2.0']
  - python-duckdb
  - pytorch-lightning
  - scipy
  - pytorch
  - torchtext
  - torchvision 
  - torchaudio 
  - numpy[version='<=1.23']
  - cython
  - scikit-learn
  - pyarrow
  - jupyterlab
  - jupyter
  - ipywidgets
  - yaml
  - selenium=3.141.0
  - altair
  - altair_saver
  - dcor
  - scanpy
  - python-igraph
  - goatools
  - python-annoy
  - pyreadr
  - matplotlib[version'>=3.4,<3.5']
  - rpy2
  - anndata2ri
  - deprecated
  - memray
